Design PropertyPro Homepage Website
Admayah/PropertyPro pull request #1
Opened 2021-11-26 10:12 UTC by Admayah

2021-12-11 23:52 UTC, olashehu requested changes

2021-12-11 23:52 UTC, olashehu commented on src/components/footer/footer.css
> +@media (min-width: 768px) {
Same as mentioned on the other PR for media query.

2021-12-11 23:52 UTC, olashehu commented on src/components/footer/footerListArray.js
> +        <a href="#" className="liLink">{listLink}</a>
What is liLink? You may want to change this class name to something like "footer-link"

2021-12-16 10:20 UTC, mykelmatics reviewed
Overall the Code looks good , Dropped some comment

2021-12-16 10:20 UTC, mykelmatics commented on public/index.html
> -    <noscript>You need to enable JavaScript to run this app.</noscript>
Why remove noscript tag

2021-12-16 10:20 UTC, mykelmatics commented on src/components/Button/button.css
> +  font-size: 20px;
I suggest you use rem on font-size

2021-12-16 10:20 UTC, mykelmatics commented on src/components/Herosection/Hero.jsx
> +            <div className="heroButtonContainer">
I suggest you use try to shorten "heroButtonContainer" to "heroBtnContainer"

2021-12-16 10:20 UTC, mykelmatics commented on src/components/Herosection/hero.css
> +  /* background-color: blue; */
remove all commented line that is not explaining the code

2021-12-16 10:20 UTC, mykelmatics commented on src/components/Herosection/hero.css
> +  /* opacity: ; */
Try remove commented line

2021-12-16 10:20 UTC, mykelmatics commented on src/components/Herosection/hero.css
> +  margin-bottom: 57px;
I suggest use rem instead of px

2021-12-16 10:20 UTC, mykelmatics commented on src/components/Herosection/hero.css
> +.TaglineText {
I suggest you try to be uniform with your className may be you should change that to camelCase

2021-12-16 10:20 UTC, mykelmatics commented on src/components/Navbar/navbar.css
> +  font-size: 18px;
change to rem

2021-12-16 10:20 UTC, mykelmatics commented on src/components/OurServicesSection/OurServices.jsx
> +            return (
why do we have return here ?

2021-12-16 10:20 UTC, mykelmatics commented on src/components/blogposts/BlogPost.jsx
> +            <div class="propertyContent">
why return

2021-12-16 10:20 UTC, mykelmatics commented on src/components/blogposts/BlogPost.jsx
> +//   <h3>Here Comes The Blog Title.</h3>
remove commented lines

2021-12-16 10:20 UTC, mykelmatics commented on src/components/blogposts/blogpost.css
> +     */
remove commented lines

2021-12-16 10:20 UTC, mykelmatics commented on src/index.css
> +  /* box-sizing: border-box; */
remove commented line

2021-12-16 11:32 UTC, Pauliski requested changes
good work

2021-12-16 11:32 UTC, Pauliski commented on src/App.css
> -.App {
Please, delete every unused CSS file or code

2021-12-16 11:32 UTC, Pauliski commented on src/App.js
> +// import Button from './components/Button/Button';
please, you can remove this if not needed

2021-12-16 11:32 UTC, Pauliski commented on src/components/Button/Button.jsx
> +        <button className="buttonWrapper">BECOME AN AGENT</button>
change all className to follow the kebab case naming convention eg. button-wrapper not buttonContainer

2021-12-16 11:32 UTC, Pauliski commented on src/components/Herosection/Hero.jsx
> +    <div className="heroContainer">
please change all className from camel case to kebab case

2021-12-16 11:32 UTC, Pauliski commented on src/components/Herosection/hero.css
> +  background-color: crimson;
you might want to stick to using #color-code for uniformity purpose

2021-12-16 11:32 UTC, Pauliski commented on src/components/OurServicesSection/OurServices.jsx
> +              <div className="serviceOffer">
I think you might like to check your console for error message also because your map item are not having a unique key

2021-12-16 11:32 UTC, Pauliski commented on src/components/blogposts/BlogPost.jsx
> +            <div class="propertyContent">
please add unique key to map items

2021-12-20 11:25 UTC, merged