Design signup and login page
Admayah/PropertyPro pull request #2
Opened 2021-11-30 13:12 UTC by Admayah

2021-12-11 23:40 UTC, olashehu requested changes

2021-12-11 23:40 UTC, olashehu commented on src/components/Button/Button.jsx
> +        <button className="buttonWrapper">BECOME AN AGENT</button>
I think wrapping a button inside of a tag is a bad practice. You may want to check out this site https://caninclude.glitch.me/ to know more about elements that can not be a child of another element.

2021-12-11 23:40 UTC, olashehu commented on src/components/Button/Button.jsx
> +    <div className="buttonContainer">
When given an element a class name, it's best practice to use Kebab-case instead of camelCase as above.
example of the Kebab-case <div className="button-container>

2021-12-11 23:40 UTC, olashehu commented on src/components/Herosection/Hero.jsx
> +    <div className="heroContainer">
Kebab-case, same as above.

2021-12-11 23:40 UTC, olashehu commented on src/components/Herosection/hero.css
> +  padding: 0 2.1875rem;
You may want to decare this padding property in one line. e.g,  padding:  3rem 2.5rem 2rem;
The first value is for the top, the second value is for both right and left and the last value is for the bottom.
Read about shorthand for padding.

2021-12-11 23:40 UTC, olashehu commented on src/components/Navbar/Navbar.jsx
> +      <a href={btn.href} className="navbarPropertyLink">
You may want to use React Link component instead of the anchor tag to avoid refreshing the page when routing to another URL within your application.

2021-12-11 23:40 UTC, olashehu commented on src/components/Navbar/navbar.css
> +@media (max-width: 768px) {
You have two same declarations for @media in a single file. I believe you are not using the style component right?
You may want to take the navbarMenu @media CSS to the upper @media.

2021-12-11 23:40 UTC, olashehu commented on src/components/OurServicesSection/OurServices.jsx
> +              <div className="serviceOffer">
Same here. Use kebab-case

2021-12-11 23:40 UTC, olashehu commented on src/components/OurServicesSection/ourservices.css
> +@media (max-width: 768px) {
Same here for the media query. You can use only one max-width 768px to achieve your goal in this file instead of duplicating it.

2021-12-11 23:40 UTC, olashehu commented on src/components/blogposts/BlogPost.jsx
> +//   <p>
You can delete commented codes if you are no longer using them before pushing online.

2021-12-16 10:40 UTC, mykelmatics reviewed
Drop some comment

2021-12-16 10:40 UTC, mykelmatics commented on src/components/Button/button.css
> +  font-size: 20px;
Change to rem

2021-12-16 10:40 UTC, mykelmatics commented on src/components/Button/button.css
> +  padding: 10px;
Change to rem

2021-12-20 11:28 UTC, merged