integrated my frontend and backend and implemented redux toolkit
Admayah/PropertyPro pull request #5
Opened 2022-07-06 11:07 UTC by Admayah

Integrated my frontend app to my backend. So, user can create an account and login to their dashboard. They User(agent) can create, view, edit and delete property he/she posted on their dashboard.

2022-07-06 22:02 UTC, nosisky commented on README.md
> +**9jaProperty** makes use of a host of modern technologies. The core ones are:
Well done for updating the README.md with installation steps.

2022-07-06 22:03 UTC, nosisky commented on src/ProtectedRoute.js
> +    console.log(localStorage.getItem('token'))
Take way the console.log statement if it's no longer needed.

2022-07-06 22:04 UTC, nosisky commented on src/components/allproperties/AllPropertiesData.jsx
> +const url = 'http://localhost:4000/v1/properties'
This API URL should be in an environment variable, research how to work with the environment variable in React. If the API URL changes, you don't always have to modify the code to reflect the changes.

2022-07-06 22:06 UTC, nosisky commented on src/components/editProperty/EditProperty.jsx
> +      const response = await axios.put('http://localhost:4000/v1/agent/properties/' + id ,{...editProperty}, config)
Same thing here, the API URL should be in an environment variable.

2022-07-06 22:06 UTC, nosisky commented on src/components/editProperty/EditProperty.jsx
> +      console.log(error)
You are suppose to toast this error message to let the user know something Is wrong, your user won't be checking your console to figure out there is a problem.

2022-07-06 22:08 UTC, nosisky requested changes
Please request for more reviews from your teammates, there are so many things that can be improved about this code, check the code yourself and make necessary improvements.

2022-07-08 10:43 UTC, olashehu requested changes
Well done, I drop some comments.

2022-07-08 10:43 UTC, olashehu commented on src/components/allproperties/PropertiesInfo.jsx
>            {" "}
Remove this line

2022-07-08 10:43 UTC, olashehu commented on src/App.js
> +    <ToastContainer />
Please, remove this if you are done testing.

2022-07-08 10:43 UTC, olashehu commented on src/ErrorPage.js
> +    <div>There's nothing here: 404!</div>
I suggest we use something like "404 - Not Found"

2022-07-08 10:43 UTC, olashehu commented on src/components/allproperties/AllPropertiesData.jsx
> +      // setProperties(AllProperties)
Please, remove this if you are not using it.

2022-07-08 10:43 UTC, olashehu commented on src/components/allproperties/AllPropertiesData.jsx
> +//  console.log(propertyItems)
Please, remove this if you are no longer using it.

2022-07-08 10:43 UTC, olashehu commented on src/components/editProperty/EditProperty.jsx
> +                  id="choces"
Typo

2022-07-08 10:43 UTC, olashehu commented on src/components/feed/Feed.jsx
> +  console.log('----->', id)
Take way the console

2022-07-08 10:43 UTC, olashehu commented on src/components/feed/Feed.jsx
> +        console.log(data)
Same here and line 38

2022-07-08 10:43 UTC, olashehu commented on src/components/feed/Feed.jsx
>                      {" "}
Take this line out

2022-07-08 10:43 UTC, olashehu commented on src/components/feed/Feed.jsx
> +        console.log(error)
Make use of toast here

2022-07-08 10:43 UTC, olashehu commented on src/components/feed/properties.js
>  export default Properties;
This file should not be inside the component folder

2022-07-08 10:43 UTC, olashehu commented on src/components/propertiesInput/PropertiesInputData.jsx
> +    }))
Please, make use of toast for success and error messages here too.

2022-07-08 10:43 UTC, olashehu commented on src/components/propertiesInput/PropertiesInputData.jsx
> +                  {/* <div>Price</div> */}
If you are not using this, remove it.

2022-07-08 10:43 UTC, olashehu commented on src/components/propertiesInput/PropertiesInputData.jsx
> +                  {/* <div className="property-location-header">Price</div> */}
Same here as above

2022-07-08 10:43 UTC, olashehu commented on src/components/propertiesInput/PropertiesInputData.jsx
> +                      // placeholder=""
Please, look in your code for anywhere you have a code commented out and remove

2022-07-08 10:43 UTC, olashehu commented on src/components/propertydetails/PropertyDetails.jsx
> +  console.log(id)
Take this away

2022-07-08 10:43 UTC, olashehu commented on src/components/rent/Rent.jsx
>                  {" "}
Same here

2022-07-08 10:43 UTC, olashehu commented on src/components/sales/Sales.jsx
>                  {" "}
Same here

2022-07-29 10:30 UTC, mykelmatics reviewed
Overall this looks good, The style and all.

2022-07-29 10:30 UTC, mykelmatics commented on src/components/Navbar/navbar.css
>  }
remove commented lines

2022-07-29 10:30 UTC, mykelmatics commented on src/components/allproperties/AllPropertiesData.jsx
> +import 'react-toastify/dist/ReactToastify.css';
I suggest you have import of packages before component

2022-07-29 10:30 UTC, mykelmatics commented on src/components/allproperties/AllPropertiesData.jsx
> +  // };
remove comment

2022-07-29 10:30 UTC, mykelmatics commented on src/components/allproperties/AllPropertiesData.jsx
> +console.log(properties)
I suggest you remove this

2022-07-29 10:30 UTC, mykelmatics commented on src/components/allproperties/propertiesdata.css
> +  /* object-fit: cover; */
remove comment

2022-07-29 10:30 UTC, mykelmatics commented on src/components/editProperty/EditProperty.jsx
> +      "headers": {
Try to format your code

2022-07-29 10:30 UTC, mykelmatics commented on src/components/feed/Feed.jsx
> +
remove comment

2022-07-29 10:30 UTC, mykelmatics commented on src/components/propertiesInput/PropertiesInputData.jsx
> +              />
I suggest you map the Input so you can reduce the lines of code here and also stick to DRY principle

2022-07-29 10:30 UTC, mykelmatics commented on src/components/propertiesInput/PropertiesInputData.jsx
> +              <label htmlFor="price">Property Description</label>
I suggest you map the input field so you can reduce the lines of code here and also stick to DRY principle

2022-07-29 10:30 UTC, mykelmatics commented on src/components/propertydetails/Features.js
> +      console.log(response)
you can remove this

2022-07-29 10:30 UTC, mykelmatics commented on src/components/propertydetails/PropertyDetails.jsx
> +
remove commented lines

2022-07-29 10:30 UTC, mykelmatics commented on src/components/rent/Rent.jsx
> +
same here

2022-07-29 10:30 UTC, mykelmatics commented on src/components/sales/Sales.jsx
> +  // console.log(rentProps)
same here

2022-07-29 10:30 UTC, mykelmatics commented on src/pages/profile/Profile.jsx
> +                {/* <div className="property-infos">
remove commented line

2022-07-29 10:30 UTC, mykelmatics commented on src/store.js
> +// import userReducer from './features/auth/slice';
same here

2022-08-04 10:43 UTC, merged